# Generated by Django 4.0 on 2023-11-17 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0002_departmentmaster_eventcategorymaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalMasterHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(max_length=100)),
                ('festival_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('festival_banner', models.CharField(blank=True, max_length=50, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.institutionmaster')),
            ],
        ),
    ]
