# Generated by Django 4.0 on 2023-11-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0004_committemembertypemaster_organizingcommittemaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_team_size', models.IntegerField(blank=True, null=True)),
                ('min_team_size', models.IntegerField(blank=True, null=True)),
                ('event_description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
                ('event_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.eventcategorymaster')),
                ('festival_master_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.festivalmasterheader')),
                ('participant_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.participantcategorymaster')),
            ],
        ),
        migrations.CreateModel(
            name='PrizeTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=50)),
                ('sponsor_logo', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WinnerPositionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_position', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start_date', models.DateField(blank=True, null=True)),
                ('event_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
                ('event_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.eventmaster')),
            ],
        ),
        migrations.CreateModel(
            name='EventPrizeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('event_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
                ('event_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.eventmaster')),
                ('prize_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.prizetypemaster')),
                ('winner_position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.winnerpositionmaster')),
            ],
        ),
    ]
