# Generated by Django 4.0 on 2023-11-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0006_participanttypemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantRegistrationHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.IntegerField()),
                ('event_chest_no', models.CharField(blank=True, max_length=20, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
                ('event_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.eventmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantRegistrationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_status', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
                ('participant_registration_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.participantregistrationheader')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantRegistrationChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100)),
                ('participant_id_no', models.CharField(blank=True, max_length=20, null=True)),
                ('participant_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('participant_id_card', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
                ('participant_registration_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.participantregistrationheader')),
                ('participant_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminMainApp.participanttypemaster')),
            ],
        ),
    ]
