# Generated by Django 4.0 on 2023-11-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0007_participantregistrationheader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
                ('event_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.eventmaster')),
                ('participant_registration_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.participantregistrationheader')),
                ('winner_position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.winnerpositionmaster')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
                ('event_result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.eventresult')),
            ],
        ),
    ]
