# Generated by Django 4.0 on 2023-11-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0008_eventresult_gallerymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=30)),
                ('login_password', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.CharField(max_length=20, null=True)),
                ('organizing_committe_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.organizingcommittemaster')),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.usertype')),
            ],
        ),
    ]
