# Generated by Django 4.0 on 2023-11-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0009_usertype_usermaster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WinnerPositionMaster',
            new_name='WinnerPositionMasterModel',
        ),
    ]
