# Generated by Django 4.0 on 2023-11-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0010_rename_winnerpositionmaster_winnerpositionmastermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrizeTypeMaster',
            new_name='PrizeTypeMasterModel',
        ),
    ]
