# Generated by Django 4.0 on 2023-12-02 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0011_rename_prizetypemaster_prizetypemastermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='organizing_committe_master_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.organizingcommittemaster'),
        ),
    ]
