# Generated by Django 4.0 on 2023-12-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0012_alter_usermaster_organizing_committe_master_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalmasterheader',
            name='institution_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminMainApp.institutionmaster'),
        ),
    ]
