# Generated by Django 4.0 on 2023-12-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0014_remove_festivalmasterheader_institution_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingcommittemaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
