# Generated by Django 4.0 on 2023-12-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0015_organizingcommittemaster_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='EventName',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
