# Generated by Django 4.0 on 2023-12-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0018_alter_eventprizemaster_cash_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprizemaster',
            name='event_cash_prize',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eventprizemaster',
            name='event_scores',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
