# Generated by Django 4.0 on 2023-12-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0019_eventprizemaster_event_cash_prize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventprizemaster',
            name='cash_amount',
        ),
        migrations.RemoveField(
            model_name='eventprizemaster',
            name='event_score',
        ),
    ]
