# Generated by Django 4.0 on 2023-12-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0021_alter_participantregistrationheader_college_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantregistrationpayment',
            name='payment_type',
            field=models.BooleanField(default=True),
        ),
    ]
