# Generated by Django 4.0 on 2024-01-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0022_participantregistrationpayment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='event_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
