# Generated by Django 4.0 on 2024-01-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0025_alter_participantregistrationheader_college_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantregistrationchild',
            name='participant_email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
