# Generated by Django 4.0 on 2024-01-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0028_eventmaster_abbreviation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantregistrationheader',
            old_name='college_id',
            new_name='college_name',
        ),
    ]
