# Generated by Django 4.0 on 2024-01-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0030_alter_participantregistrationchild_participant_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaster',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
         migrations.AddField(
            model_name='eventmaster',
            name='max_registration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='video_file',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='festivalmasterheader',
            name='video_file',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='participantregistrationheader',
            name='reference_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantregistrationpayment',
            name='registration',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participantregistrationpayment',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsormaster',
            name='sponsor_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]

