# Generated by Django 4.0 on 2024-02-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMainApp', '0033_menuchild_is_active_menuheader_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuchild',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
