from . import views
from django.urls import path
from .views import GetEventCategoriesView,GetParticipantCategory,GetEventMaster

urlpatterns = [
    path('home', views.home, name='home'),
    path("login",views.login,name="login"),
    path("login",views.login,name="login"),
    # Department Master
    path('create_department',views.create_department,name="create_department"),
    path('viewdepartment',views.view_department,name="viewdepartment"),
    path('updatedepartment/<str:id>',views.update_department,name="updatedepartment"),
    path('deletedepartment/<str:id>',views.delete_department,name="updatedepartment"),
    path('DeleteDepartment1/<str:id>',views.delete_department1,name="updatedepartment"),
    #event category
    path('CreateEventCategory',views.Create_Event_Category,name="CreateEventDepartment"),
    path('vieweventcategory',views.view_event_category,name="vieweventcategory"),
    path('EditEventCategory/<str:id>',views.edit_event_category,name="editeventcategory"),
    path("DeleteEventCategory/<str:id>",views.delete_event_category,name="DeleteEventCategory"),
    path('DeleteEventCategory1/<str:id>',views.delete_event_category1,name="DeleteEventCategory1"),
    # User type
    path('CreateUserType',views.CreateUserType.as_view(),name="CreateUserType"),
    path('EditUserType/<str:id>',views.EditUserType.as_view(),name="EditUserType"),
    path('DeleteUserType/<str:id>',views.DeleteUserType.as_view(),name="DeleteUserType"),
    path('DeleteUserType1/<str:id>',views.DeleteUserType1,name="DeleteUserType1"),
    # User Master
    # path('ViewUserType',views.view_user_type,name="ViewUserType"),
    path('CreateUserMaster',views.CreateUserMaster.as_view(),name="CreateUserMaster"),
    path('CreateUserMaster1',views.CreateUserMaster1.as_view(),name="CreateUserMaster1"),
    path('ViewUserMaster/<str:id>',views.view_user_master,name="ViewUserMaster"),
    path('EditUserMaster/<str:id>',views.EditUserMaster.as_view(),name="EditUserMaster"),
    path('DeleteUserMaster/<str:id>',views.delete_user_master,name="DeleteUserMaster"),
    path('DeleteUserMaster1/<str:id>',views.delete_user_master1,name="DeleteUserMaster"),
    path('get_committe_member/',views.GetCommitteMember.as_view(),name="get_committe_member"),
    # Committe Member Type Master
    path('CreateCommitteMasterType',views.CreateCommitteMasterType.as_view(),name="CreateCommitteMasterType"),
    path('EditCommitteMasterType/<str:id>',views.edit_committe_master_type,name="EditCommitteeMasterType"),
    path('DeleteCommitteMasterType/<str:id>',views.delete_committe_master_type,name="DeleteCommitteMasterType"),
    path('DeleteCommitteMasterType1/<str:id>',views.delete_committe_master_type1,name="DeleteCommitteMasterType1"),
    # Institution Master
    path('CreateInstitution',views.CreateInstitution.as_view(),name="CreateInstitution"),
    path('ViewInstitution',views.view_institution,name="ViewInstitution"),
    path('EditInstitution/<str:id>',views.EditInstitution.as_view(),name="EditInstitution"),
    path('DeleteInstitution/<str:id>',views.delete_institution,name="DeleteInstitution"),
    path('DeleteInstitution1/<str:id>',views.delete_institution1,name="DeleteInstitution1"),
    # Participant Category Master
    path('ParticipantCategoryMaster',views.view_participant_category,name="ParticipantCategoryMaster"),
    path('CreateParticipantCategory',views.create_participant_category,name="CreateParticipantCategory"),
    path('EditParticipantCategory/<str:id>',views.EditParticipantCategory.as_view(),name="EditParticipantCategory"),
    path('DeleteParticipantCategory/<str:id>',views.delete_participant_category,name="DeleteParticipantCategory"),
    path('DeleteParticipantCategory1/<str:id>',views.delete_participant_category1,name="DeleteParticipantCategory1"),
    # Participant Type Master
    path('ViewParticipantTypeMaster',views.ViewParticipantTypeMaster.as_view(),name="ViewParticipantTypeMaster"),
    path("EditParticipantType/<str:id>",views.EditParticipantType.as_view(),name="EditParticipantType"),
    path('DeleteParticipantType/<str:id>',views.delete_participant_type,name="DeleteParticipantType"),
    path('DeleteParticipantType1/<str:id>',views.delete_participant_type1,name="DeleteParticipantType1"),
    # Winner Position Master
    path('ViewWinnerPosition',views.view_winner_position,name="ViewWinnerPosition"),
    path('WinnerPositionMaster',views.WinnerPositionMaster.as_view(),name="WinnerpostionMaster"),
    path("EditWinnerPosition/<str:id>",views.EditWinnerPosition.as_view(),name="EditWinnerPosition"),
    path('DeleteWinnerPosition/<str:id>',views.delete_winner_position,name="DeleteWinnerPosition"),
    path('DeleteWinnerPosition1/<str:id>',views.delete_winner_position1,name="DeleteWinnerPosition1"),
    # Prize Type Master
    path('ViewPrizeTypeMaster',views.ViewPrizeTypeMaster.as_view(),name="ViewPrizeTypeMaster"),
    path("EditPrizeType/<str:id>",views.EditPrizeType.as_view(),name="EditPrizeType"),
    path('DeletePrizeType/<str:id>',views.delete_prize_type,name="DeletePrizeType"),
    path('DeletePrizeType1/<str:id>',views.delete_prize_type1,name="DeletePrizeType1"),
    # Sponsor Master
    path('ViewSponsorMaster',views.ViewSponsorMaster.as_view(),name="ViewSponsorMaster"),
    path("EditSponsorMaster/<str:id>",views.EditSponsorMaster.as_view(),name="EditSponsorMaster"),
    path('DeleteSponsorMaster/<str:id>',views.delete_sponsor_master,name="DeleteSponsorMaster"),
    path('DeleteSponsorMaster1/<str:id>',views.delete_sponsor_master1,name="DeleteSponsorMaster"),
    path('get_festival_event/',views.get_festival_event.as_view(),name="get_festival_event"),
    # Festival Master
    path('CreateFestivalMaster',views.CreateFestivalMaster.as_view(),name="CreateFestivalMaster"),
    path('ViewFestivalMaster',views.view_festival_master,name="ViewFestivalMaster"),
    path('EditFestivalMaster/<str:id>',views.EditFestivalMaster.as_view(),name="EditFestivalMaster"),
    path("DeleteFestivalMaster/<str:id>",views.delete_festival_master,name="DeleteFestivalMaster"),
    path("DeleteFestivalMaster1/<str:id>",views.delete_festival_master1,name="DeleteFestivalMaster1"),
    # Organizing Committe Master
    path('CreateOrganizingCommitte',views.CreateOrganizingCommitte.as_view(),name="CreateOrganizingCommitte"),
    path("ViewOrganizingCommitte",views.view_organizing_committe,name="ViewOrganizingCommitte"),
    path("EditOrganizingCommitte/<str:id>",views.EditOrganizingCommitte.as_view(),name="EditOrganzingCommitte"),
    path("DeleteOrganizingCommitte/<str:id>",views.delete_organizing_committe,name="DeleteOrganizingCommitte"),
    path("DeleteOrganizingCommitte1/<str:id>",views.delete_organizing_committe1,name="DeleteOrganizingCommitte1"),
    # Event Master
    path('CreateEventMaster',views.CreateEventMaster.as_view(),name="CreateEventMaster"),
    path("ViewEventMaster",views.view_event_master,name="ViewEventMaster"),
    path("EditEventMaster/<str:id>",views.EditEventMaster.as_view(),name="EditEventMaster"),
    path("DeleteEventMaster/<str:id>",views.delete_event_master,name="DeleteEventMaster"),
    path("DeleteEventMaster1/<str:id>",views.delete_event_master1,name="DeleteEventMaster1"),
    # Event Scheduler
    path('CreateEventScheduler',views.CreateEventScheduler.as_view(),name="CreateEventScheduler"),
    path("ViewEventScheduler",views.view_event_scheduler,name="ViewEventScheduler"),
    path("EditEventScheduler/<str:id>",views.EditEventScheduler.as_view(),name="EditEventScheduler"),
    path("DeleteEventScheduler/<str:id>",views.delete_event_scheduler,name="DeleteEventScheduler"),
    path("DeleteEventScheduler1/<str:id>",views.delete_event_scheduler1,name="DeleteEventScheduler1"),
    path('get_event_categories/', GetEventCategoriesView.as_view(), name='get_event_categories'),
    path('get_participant_categories/', GetParticipantCategory.as_view(), name='get_participant_categories'),
    path('get_event_master/', GetEventMaster.as_view(), name='get_event_master'),
    # Event Prize Master
    path('CreateEventPrize',views.CreateEventPrize.as_view(),name="CreateEventPrize"),
    path("ViewEventPrize",views.view_event_prize,name="ViewEventPrize"),
    path("EditEventPrize/<str:id>",views.EditEventPrize.as_view(),name="EditEventPrize"),
    path("DeleteEventPrize/<str:id>",views.delete_event_prize,name="DeleteEventPrize"),
    path("DeleteEventPrize1/<str:id>",views.delete_event_prize1,name="DeleteEventPrize1"),
    # Participant Registartion
    path("CreateParticipantRegistartion",views.CreateParticipantRegistartion.as_view(),name="CreateParticipantRegistartion"),
    path("ViewParticipantRegistration",views.view_participant_registration,name="ViewParticipantRegistration"),
    path('get_event_master_for_participant/',views.GetEventMasterForParticipant.as_view(), name='get_event_master_for_participant'),
    path('get_registration_fee/', views.GetRegistrationFee.as_view(), name='get_registration_fee'),
    path('GeneratePaymentReceipt',views.GeneratePaymentReceipt,name="GeneratePaymentReceipt"),
    path('GeneratePaymentReceipt_Admin',views.GeneratePaymentReceipt_Admin,name="GeneratePaymentReceipt_Admin"),
    path('ParticipantListEdit1/<str:id>',views.ParticipantListEdit1.as_view(),name="ParticipantListEdit1"),
    path('ParticipantListDelete/<str:id>',views.participant_list_delete,name="ParticipantListDelete"),
    path('ParticipantListDelete1/<str:id>',views.participant_list_delete1,name="ParticipantListDelete1"),
    # Event Result
    path('CreateEventResult',views.CreateEventResult.as_view(),name="CreateEventResult"),
    path("ViewEventResult",views.view_event_result,name="ViewEventResult"),
    path("EditEventResult/<str:id>",views.EditEventResult.as_view(),name="EditEventResult"),
    path("DeleteEventResult/<str:id>",views.delete_event_result,name="DeleteEventResult"),
    path("DeleteEventResult1/<str:id>",views.delete_event_result1,name="DeleteEventResult1"),
    path('get_participant_names/', views.get_participant_names, name='get_participant_names'),
    path('get_participant_names1/', views.get_participant_names1, name='get_participant_names1'),
    path('participant_name/',views.participant_name,name="participant_name"),
    path('initiate_payment/', views.initiate_payment, name='initiate_payment'),
    path('payment_success/', views.payment_success, name='payment_success'),
    # Gallery Master
    path('CreateGalleryMaster',views.CreateGalleryMaster.as_view(),name="CreateGalleryMaster"),
    path("ViewGalleryMaster",views.view_gallery_master,name="ViewGalleryMaster"),
    path("EditGalleryMaster/<str:id>",views.EditGalleryMaster.as_view(),name="EditGalleryMaster"),
    path("DeleteGalleryMaster/<str:id>",views.delete_gallery_master,name="DeleteGalleryMaster"),
    path("DeleteGalleryMaster1/<str:id>",views.delete_gallery_master1,name="DeleteGalleryMaster1"),
    #
    #____________________________________Student Home___________________________________________
    path('',views.student_home,name="StudentHome"),
    path('StudentHome',views.student_home,name="StudentHome"),
    path('StudentViewEvent/<str:id>',views.StudentViewEvents.as_view(),name="StudentViewEvents"),
    path('StudentRegisterEvent/<str:id>',views.StudentRegisterEvent.as_view(),name="StudentRegisterEvent"),
    path('create_order/', views.create_order, name='create_order'),
    path('verify_payment/', views.verify_payment, name='verify_payment'),
    path('PaySlip',views.Student_pay_slip,name="Payslip"),
    path('Slip',views.Slip,name="Slip"),
    # path('create_transfer/',views.create_transfer,name="create_transfer"),
    #-----------------------------------------Reports----------------------------------
    #ParticipantList
    path('participantlist',views.participantlist,name="participantlist"),
    path('ParticipantListEdit/<str:id>',views.ParticipantListEdit.as_view(),name="ParticipantListEdit"),
    path('get_festival_participant/',views.GetFestivalParticipant.as_view(),name="get_festival_participant"),
    path('ParticipantListReport',views.participant_list_report,name="ParticipantListReport"),
    path('get_event_category_list/',views.GetEventListCategoriesView.as_view(), name='get_event_category_list'),
    path('get_participant_list_category/',views.GetParticipantListCategory.as_view(), name='get_participant_list_category'),
    path('get_event_master_list/',views.GetEventMasterList.as_view(), name='get_event_master_list'),
    #Account Report
    path('AccountReport',views.account_report,name="AccountReport"),
    path("get_account_report_year/",views.GetAccountReportYear.as_view(),name="get_account_report_year"),
    path('get_account_report_festival_wise/',views.GetAccountReportFestivalWise.as_view(),name="get_account_report_festival_wise"),
    path('get_account_report_event_wise/',views.GetAccountReportEventWise.as_view(),name="get_account_report_event_wise"),
    #Result Report
    path('ResultReport',views.result_report,name="ResultReport"),
    path('get_result_report/',views.GetResultReport,name="get_result_report"),
    path('get_result_report_festival/',views.GetResultReportFestival.as_view(),name="get_result_report_festival"),
    path('get_result_event_wise/',views.GetResultEventWise.as_view(),name="get_result_event_wise"),
    #Referral Report
    path('ReferralReport',views.referal_report,name="ReferralReport"),
    path('get_referral_report/',views.GetReferrealReport.as_view(),name="get_referral_report"),
    path('get_refferal_report_event_wise/',views.GetRefferalReportEventwise.as_view(),name="get_refferal_report_event_wise"),

    path('staticscreen',views.participant_statistics_report,name="staticscreen"),
    path('get_event_master_report/',views.GetEventMasterReport.as_view(),name="get_event_master_report"),
    path('CollegeReport',views.college_report,name="CollegeReport"),
    path('OverallPointWiseReport',views.overall_point_wise_report,name="OverallPointWiseReport"),
    path('SpotRegistrationReport',views.spot_registration_report,name="SpotRegistrationReport"),
    #------------------------------------------------------
    path('StatisticsScreen',views.participant_statistics_report,name="StatisticsScreen"),
    path('getcategorytype/',views.getcategorytype,name="getcategorytype"),
    path('event_wise_participant_list/',views.GetParticipantView.as_view(),name="eventwiseparticipantlist"),
    path('get_event_master_report/',views.GetEventMasterReport.as_view(),name="get_event_master_report"),
    path('get_college_report/',views.GetCollegeReport.as_view(),name="get_college_report"),
    path('get_college_report1/',views.GetCollegeReport1.as_view(),name="get_college_report1"),
    path('get_college_report2/',views.GetCollegeReport2.as_view(),name="get_college_report2"),
    path('get_event_names/',views.GetEventNames.as_view(),name="get_event_names"),
    path('spot_registration_report/',views.SpotRegistrationReportView.as_view(),name="spot_registration_report"),

    path('get_result_report_festival/',views.GetResultReportFestival.as_view(),name="get_result_report_festival"),
    path('get_overall_pointwise_report/',views.get_overall_pointwise_report,name="get_overall_pointwise_report"),
    #Menu Header
    path('ViewMenuHeader',views.ViewMenuHeader.as_view(),name="ViewMenuHeader"),
    path('EditMenuHeader/<str:id>',views.EditMenuHeader.as_view(),name="EditMenuHeader"),
    path('DeleteMenuHeader/<str:id>',views.delete_menu_header,name="DeleteMenuHeader"),
    path('DeleteMenuHeader1/<str:id>',views.delete_menu_header1,name="DeleteMenuHeader1"),
    #Menu Child
    path('CreateMenuChild/<str:id>',views.CreateMenuChild.as_view(),name="CreateMenuChild"),
    path('ViewMenuChild/<str:id>',views.view_menu_child,name="ViewMenuChild"),
    path('EditMenuChild/<str:id>',views.EditMenuChild.as_view(),name="EditMenuChild"),
    path('DeleteMenuChild/<str:id>',views.delete_menu_child,name="DeleteMenuChild"),
    path('DeleteMenuChild1/<str:id>',views.delete_menu_child1,name="DeleteMenuChild1"),

]
